name: Check Markdown links
on: 
  workflow_dispatch:
  schedule: 
  - cron: '* */24 * * *'
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        with:
          config-file: '.mlc_config.json'
          folder-path: "docs"
